version: '2'

services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=solder
      - MYSQL_USER=solder
      - MYSQL_PASSWORD=solder

  web:
    image: nginx
    restart: always
    depends_on:
      - php
    ports:
      - 8080:80
    volumes:
      - ./solder:/home/solder
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./phpfpm
    restart: always
    volumes:
      - ./solder:/home/solder
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=solder
      - DB_USERNAME=solder
      - DB_PASSWORD=solder

  migrate:
    build: ./phpfpm
    restart: "no"
    volumes:
      - ./solder:/home/solder
    depends_on:
      - db
    working_dir: /home/solder
    command: php artisan migrate --force --seed
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=solder
      - DB_USERNAME=solder
      - DB_PASSWORD=solder

  install:
    image: composer
    restart: "no"
    volumes:
      - ./solder:/home/solder
    working_dir: /home/solder
    command: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=solder
      - DB_USERNAME=solder
      - DB_PASSWORD=solder
